### ISSUE TITLE
Create list of topics to bag

### ISSUE THREAD

**Issue by javatechs** [ProgrammingRobotsStudyGroup/robo_magellan#10]
Create list of topics to bag. See attached list as baseline.
[b4_rostopiclist.txt](https://github.com/ProgrammingRobotsStudyGroup/robo_magellan/files/913594/b4_rostopiclist.txt)

**Comment by kennethjiang** [comment]
I guess I need input from everyone who has written code to subscribe/publish messages to send me a list of topics their code makes use of. What's the best way to go about it?

**Comment by javatechs** [comment]
@kenneth the attachment [b4_rostopiclist.txt](https://github.com/ProgrammingRobotsStudyGroup/robo_magellan/files/913594/b4_rostopiclist.txt) already contains the list of topics.

**Comment by kennethjiang** [comment]
I thought the txt file is the list of all the topics. No? What am I supposed to do here?

**Comment by javatechs** [comment]
From the list of topics, select the ones you'd like bagged.

**Comment by kennethjiang** [comment]
Well I was hoping everyone who has written code to subscribe/publish messages can send me a list of topics they are using, so that I can construct the proper `rosbag` command to capture the right messages. That way I will be able to debug the code without having physical access to the bot.

But that's fine. It looks like I won't have too much time to dig into the code anyway. let's just close this ticket unless you find it useful in anyway that I didn't anticipate.
